"""One Markdown report with everything: risk, changes, checklist, function-level matches."""
from __future__ import annotations

from app.services.fnimpact import get_field


def _cell(text) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def build_full_markdown(analysis_id: int, project_name: str, created, result: dict,
                        fn_changes: list[dict]) -> str:
    result = result or {}
    lines: list[str] = []
    lines.append(f"# DriftAI report: analysis #{analysis_id}")
    lines.append("")
    when = created.strftime("%Y-%m-%d %H:%M UTC") if hasattr(created, "strftime") else str(created or "")
    lines.append(f"Project: **{project_name}**  ·  Created: {when}")
    lines.append("")

    risk = result.get("risk") or {}
    if risk:
        lines.append(f"**Risk: {str(risk.get('level', '')).upper()} ({risk.get('score', 0)}/100)**")
        lines.append("")
        for r in risk.get("reasons", []):
            lines.append(f"- {r}")
        lines.append("")

    changes = result.get("changes", [])
    lines.append("## What changed")
    lines.append("")
    if not changes:
        lines.append("No requirement changes were detected.")
    else:
        lines.append("| Entity | Property | Old | New |")
        lines.append("|---|---|---|---|")
        for ch in changes:
            lines.append("| {} | {} | {} | {} |".format(
                _cell(get_field(ch, "entity", default="-")),
                _cell(get_field(ch, "property", "prop", default="-")),
                _cell(get_field(ch, "old_value", "old", default="-")),
                _cell(get_field(ch, "new_value", "new", default="-"))))
    lines.append("")

    plan = result.get("action_plan", [])
    lines.append("## Action checklist")
    lines.append("")
    if not plan:
        lines.append("No actions.")
    for item in plan:
        conf = item.get("confidence")
        tag = f" (confidence: {conf})" if conf else ""
        lines.append(f"- [ ] {item.get('text', '')}{tag}")
        if item.get("reason"):
            lines.append(f"  - Why: {item['reason']}")
        if item.get("evidence"):
            lines.append(f"  - Evidence: `{item['evidence']}`")
    lines.append("")

    lines.append("## Function-level matches")
    lines.append("")
    if not fn_changes:
        lines.append("No function-level data.")
    for ch in fn_changes:
        lines.append(f"### {ch['entity']} · {ch['property']}: {ch['old_value']} -> {ch['new_value']}")
        lines.append("")
        if not ch["matches"]:
            weak = len(ch["weak_matches"])
            extra = f" ({weak} weak match(es) were hidden)" if weak else ""
            lines.append(f"No strong match found.{extra}")
        for m in ch["matches"]:
            lines.append(f"- **{m['qualname']}** ({m['kind']}, {m['confidence']}) at "
                         f"`{m['path']}:{m['start_line']}-{m['end_line']}`")
            for r in m["reasons"]:
                lines.append(f"  - {r}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by DriftAI. Suggestions are based on keywords, numbers and code structure. "
                 "Please verify each item before changing code.")
    return "\n".join(lines) + "\n"